"""empty message

Revision ID: 1d867b410e1d
Revises: 26e2a857c528
Create Date: 2025-02-27 04:34:42.048933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d867b410e1d'
down_revision = '26e2a857c528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_table('user_principal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('first_last_name', sa.String(length=80), nullable=False),
    sa.Column('second_last_name', sa.String(length=80), nullable=False),
    sa.Column('nacionality', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('birthdate', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=80), nullable=False),
    sa.Column('facebook', sa.String(length=80), nullable=True),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('x', sa.String(length=80), nullable=True),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergy', sa.String(length=80), nullable=True),
    sa.Column('disease', sa.String(length=80), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=80), nullable=False),
    sa.Column('home_country', sa.String(length=80), nullable=False),
    sa.Column('country_of_residence', sa.String(length=80), nullable=False),
    sa.Column('country_of_destination', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('zip_code', sa.String(length=80), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=80), nullable=True),
    sa.Column('longitude', sa.String(length=80), nullable=True),
    sa.Column('user_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id'], ['user_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coordinate')
    op.drop_table('user_principal')
    op.drop_table('administrator')
    # ### end Alembic commands ###
