"""empty message

Revision ID: 23d5514dd7b5
Revises: f31606d38f61
Create Date: 2025-02-27 22:36:46.541721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23d5514dd7b5'
down_revision = 'f31606d38f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_last_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('second_last_name', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('second_last_name')
        batch_op.drop_column('first_last_name')

    # ### end Alembic commands ###
