"""empty message

Revision ID: 288c7dc80f2b
Revises: dc32567e9df3
Create Date: 2025-02-18 22:45:35.344748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288c7dc80f2b'
down_revision = 'dc32567e9df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_constraint('user_principal_email_key', type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('user_principal_email_key', ['email'])

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
