"""empty message

Revision ID: 2be37be1342b
Revises: e6d3fde93b24
Create Date: 2025-02-22 03:57:56.924124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2be37be1342b'
down_revision = 'e6d3fde93b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.drop_column('migrant_or_family')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrant_or_family', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
