"""empty message

Revision ID: 36843dc26ded
Revises: 89724b409285
Create Date: 2025-02-27 23:25:10.097556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36843dc26ded'
down_revision = '89724b409285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.alter_column('nacionality',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.alter_column('nacionality',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
