"""empty message

Revision ID: 41aa1424a8b4
Revises: 4a6d43c75b96
Create Date: 2025-02-20 01:43:10.798755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aa1424a8b4'
down_revision = '4a6d43c75b96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('birthdate',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('birthdate',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
