"""empty message

Revision ID: 4a6d43c75b96
Revises: 7c78817bb792
Create Date: 2025-02-19 03:32:49.334839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6d43c75b96'
down_revision = '7c78817bb792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('organization_name')
    )
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_additional_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('street', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_clinical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergy', sa.String(length=80), nullable=True),
    sa.Column('disease', sa.String(length=80), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_contact_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_general_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('first_last_name', sa.String(length=80), nullable=False),
    sa.Column('second_last_name', sa.String(length=80), nullable=False),
    sa.Column('nacionality', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=15), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('coordinate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('user_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id'], ['user_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook', sa.String(length=80), nullable=True),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('x', sa.String(length=80), nullable=True),
    sa.Column('contact_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_data_id'], ['family_contact_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_country', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('country_of_residence', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('country_of_destination', sa.String(length=80), nullable=False))
        batch_op.drop_column('country')

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=250),
               existing_nullable=False)

    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('administrator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'administrator', ['administrator_id'], ['id'])
        batch_op.create_foreign_key(None, 'family', ['family_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('administrator_id')
        batch_op.drop_column('family_id')

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('country_of_destination')
        batch_op.drop_column('country_of_residence')
        batch_op.drop_column('home_country')

    op.drop_table('family_social_media')
    op.drop_table('coordinate')
    op.drop_table('family_general_data')
    op.drop_table('family_contact_data')
    op.drop_table('family_clinical_data')
    op.drop_table('family_additional_data')
    op.drop_table('family')
    op.drop_table('administrator')
    # ### end Alembic commands ###
