"""empty message

Revision ID: 52669bb86a62
Revises: b2c274827b6d
Create Date: 2025-02-27 22:56:21.375864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52669bb86a62'
down_revision = 'b2c274827b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###
