"""empty message

Revision ID: 56920f951b2c
Revises: 52669bb86a62
Create Date: 2025-02-27 23:00:50.605055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56920f951b2c'
down_revision = '52669bb86a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_type', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('allergy', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('disease', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('disease')
        batch_op.drop_column('allergy')
        batch_op.drop_column('blood_type')

    # ### end Alembic commands ###
