"""empty message

Revision ID: 5b0458f5a631
Revises: 1d867b410e1d
Create Date: 2025-02-27 04:52:23.364875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0458f5a631'
down_revision = '1d867b410e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('migrant_or_family', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('migrant_or_family')

    # ### end Alembic commands ###
