"""empty message

Revision ID: 6de37183aeef
Revises: 5b0458f5a631
Create Date: 2025-02-27 04:52:59.057690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de37183aeef'
down_revision = '5b0458f5a631'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.alter_column('migrant_or_family',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.alter_column('migrant_or_family',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
