"""empty message

Revision ID: 7c78817bb792
Revises: 288c7dc80f2b
Create Date: 2025-02-19 01:37:28.501791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c78817bb792'
down_revision = '288c7dc80f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('street', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('user_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id'], ['user_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=5), nullable=True),
    sa.Column('allergy', sa.String(length=80), nullable=True),
    sa.Column('disease', sa.String(length=80), nullable=True),
    sa.Column('user_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id'], ['user_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('user_principal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id'], ['user_principal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook', sa.String(length=80), nullable=True),
    sa.Column('instagram', sa.String(length=80), nullable=True),
    sa.Column('x', sa.String(length=80), nullable=True),
    sa.Column('contact_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_data_id'], ['contact_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_principal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_principal', ['user_principal_id'], ['id'])

    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_constraint('user_principal_general_data_id_fkey', type_='foreignkey')
        batch_op.drop_column('general_data_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_data_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_principal_general_data_id_fkey', 'general_data', ['general_data_id'], ['id'])

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_principal_id')

    op.drop_table('social_media')
    op.drop_table('contact_data')
    op.drop_table('clinical_data')
    op.drop_table('additional_data')
    # ### end Alembic commands ###
