"""empty message

Revision ID: 89724b409285
Revises: 56920f951b2c
Create Date: 2025-02-27 23:08:15.861868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89724b409285'
down_revision = '56920f951b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('gender')
        batch_op.drop_column('nationality')

    # ### end Alembic commands ###
