"""empty message

Revision ID: a8871aaf61cf
Revises: 2be37be1342b
Create Date: 2025-02-23 04:35:16.853509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8871aaf61cf'
down_revision = '2be37be1342b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=False))

    with op.batch_alter_table('family_additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_additional_data', schema=None) as batch_op:
        batch_op.drop_column('state')

    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
