"""empty message

Revision ID: b2c274827b6d
Revises: 23d5514dd7b5
Create Date: 2025-02-27 22:47:54.584921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c274827b6d'
down_revision = '23d5514dd7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('x', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('x')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')

    # ### end Alembic commands ###
