"""empty message

Revision ID: bf5c0b3d19c2
Revises: 98874bae38a1
Create Date: 2025-03-21 23:49:37.943288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c0b3d19c2'
down_revision = '98874bae38a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_email_key', type_='unique')
        batch_op.drop_constraint('contact_full_name_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.create_unique_constraint('contact_full_name_key', ['full_name'])
        batch_op.create_unique_constraint('contact_email_key', ['email'])

    # ### end Alembic commands ###
