"""empty message

Revision ID: cb1927cff5ed
Revises: 41aa1424a8b4
Create Date: 2025-02-22 02:39:53.015183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = 'cb1927cff5ed'
down_revision = '41aa1424a8b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DROP TABLE contact_data CASCADE"))
    op.execute(text("DROP TABLE family_contact_data CASCADE"))
    op.drop_table('social_media')
    op.drop_table('family_social_media')
    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.alter_column('country_of_destination', type_=sa.Integer(), existing_type=sa.String(), postgresql_using='country_of_destination::integer'),
        batch_op.drop_column('street')

    with op.batch_alter_table('coordinate', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=80),
               existing_nullable=True)

    with op.batch_alter_table('family_general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('facebook', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('x', sa.String(length=80), nullable=True))

    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('facebook', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('x', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('migrant_or_family', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.drop_column('migrant_or_family')
        batch_op.drop_column('x')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('family_general_data', schema=None) as batch_op:
        batch_op.drop_column('x')
        batch_op.drop_column('instagram')
        batch_op.drop_column('facebook')
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('coordinate', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.String(length=80),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.String(length=80),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.alter_column('country_of_destination',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('address')

    op.create_table('family_social_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('facebook', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('x', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('contact_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_data_id'], ['family_contact_data.id'], name='family_social_media_contact_data_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='family_social_media_pkey')
    )
    op.create_table('social_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('facebook', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('instagram', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('x', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('contact_data_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_data_id'], ['contact_data.id'], name='social_media_contact_data_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='social_media_pkey')
    )
    op.create_table('family_contact_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['family.id'], name='family_contact_data_family_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='family_contact_data_pkey')
    )
    op.create_table('contact_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_principal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_principal_id'], ['user_principal.id'], name='contact_data_user_principal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contact_data_pkey')
    )
    # ### end Alembic commands ###
