"""empty message

Revision ID: dc32567e9df3
Revises: 26e2a857c528
Create Date: 2025-02-18 04:32:37.696019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc32567e9df3'
down_revision = '26e2a857c528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('first_last_name', sa.String(length=80), nullable=False),
    sa.Column('second_last_name', sa.String(length=80), nullable=False),
    sa.Column('nacionality', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.String(length=80), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_principal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('general_data_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['general_data_id'], ['general_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_principal')
    op.drop_table('general_data')
    # ### end Alembic commands ###
