"""empty message

Revision ID: e6d3fde93b24
Revises: cb1927cff5ed
Create Date: 2025-02-22 03:10:35.266093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d3fde93b24'
down_revision = 'cb1927cff5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.alter_column('country_of_destination',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('family_additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.drop_column('street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_additional_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('address')

    with op.batch_alter_table('additional_data', schema=None) as batch_op:
        batch_op.alter_column('country_of_destination',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
