"""empty message

Revision ID: f31606d38f61
Revises: 6de37183aeef
Create Date: 2025-02-27 21:24:48.889341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31606d38f61'
down_revision = '6de37183aeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.drop_column('country_of_destination')
        batch_op.drop_column('country_of_residence')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('x')
        batch_op.drop_column('instagram')
        batch_op.drop_column('address')
        batch_op.drop_column('migrant_or_family')
        batch_op.drop_column('birthdate')
        batch_op.drop_column('nationality')
        batch_op.drop_column('blood_type')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('gender')
        batch_op.drop_column('allergy')
        batch_op.drop_column('first_last_name')
        batch_op.drop_column('disease')
        batch_op.drop_column('second_last_name')
        batch_op.drop_column('facebook')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('home_country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_country', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('facebook', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('second_last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('disease', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('allergy', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=15), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('blood_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('migrant_or_family', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('instagram', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('x', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country_of_residence', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country_of_destination', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
